### ISSUE TITLE
memory leaks when process or IOC exits.

### ISSUE THREAD

**Issue by mrkraimer** [epics-base/pvDatabaseCPP#35]
I see that pvDatabaseCPP has not been updated at since Michael gave procedures for deprecating the destroy methods.

When an IOC or process using a PVDatanase exits lots of memory is leaked.
I will start looking for places where weak pointers should be used.
This should be the key to getting rid of the memory leaks.

**Comment by mdavidsaver** [comment]
I would suggest that you investigate ```reftrack.h```.  In the context of an IOC, the ```refsave``` and ```refdiff``` commands (cf. reftrackioc.cpp in pvAccessCPP) can be used to eg. show changes in ref counts after a client has connected and disconnected.  This can give a better idea of when a leak is happening as opposed to waiting until process exit for valgrind to tell you that something went wrong.  Let me know if you have questions about how to apply this.

**Comment by mrkraimer** [comment]
For my test:
```
mrk> pwd
/home/epicsv4/masterCPP/exampleCPP/database/iocBoot/exampleDatabase
mrk> ../../bin/linux-x86_64/exampleDatabase st.cmd
```
I entered
```
epics> refshow
 BlockingUDPTransport : 6
 ChannelProvider (ABC) : 2
 Field : 124
 PDBProvider : 1
 PVField : 484
 ResponseHandler (ABC) : 19
 ServerContextImpl : 1
 Transport (ABC) : 6
epics> 

```

I used it before and after starting clients and again after exiting clients.
I also issued it after using PVRremoveRecord to remove a record.
The refshow  output was just what I expected.
Really nice command!!!
Thanks

**Comment by mrkraimer** [comment]
Implemented by latest pull request.
