### ISSUE TITLE
rtemsTestHarness.c can be simplified

### ISSUE THREAD

**Issue by mdavidsaver** [epics-base/pvDatabaseCPP#39]
`test/rtemsTestHarness.c` can be simplified to use the RTEMS configuration from libCom instead of custom config/code.  This would help @hjunkes with porting to RTEMS 5 (epics-base/epics-base#23).

`testApp/rtemsTestHarness.c` in pvAccessCPP has already been simplified in this way.  cf. epics-base/pvAccessCPP@8d262fc9fe48965a499979a4dbdeaa8973a5100b and epics-base/pvAccessCPP@93196e63148b141fe169c233ff1d299ed5a5037d

**Comment by mdavidsaver** [comment]
The specific issue is discussed https://github.com/epics-base/epics-base/pull/23#issuecomment-473201609

**Comment by mrkraimer** [comment]
Heinz
Can you make the change?

**Comment by hjunkes** [comment]
Done.
