### ISSUE TITLE
PostHandler not reset after removing record

### ISSUE THREAD

**Issue by sveseli** [epics-base/pvDatabaseCPP#44]
It seems like removing a PV record does not actually result in reseting postHandler. If the record is removed and then added again with the same PV structure, this results in "already registered" exception. From what I see, the only relevant call that is made in the 7.0.2.2 code is setPostHandler(), which is called in PVRecordField::init():

```
bluegill2> pwd
/local/sveseli/CTLSDAQ/support-7.0-rhel7/opt/epics/base/modules/pvDatabase/src/database
bluegill2> grep -i PostHandler *
pvRecord.cpp:    pvField.lock()->setPostHandler(shared_from_this());
bluegill2> 
```

Removal of the record destroys database map entry, but destructor does not seem to have any calls that would remove postHandler. Here is the method that removes record:

```
bool PVDatabase::removeRecord(PVRecordPtr const & record)
{
    if(record->getTraceLevel()>0) {
        cout << "PVDatabase::removeRecord " << record->getRecordName() << endl;
    }
    epicsGuard<epics::pvData::Mutex> guard(mutex);
    string recordName = record->getRecordName();
    PVRecordMap::iterator iter = recordMap.find(recordName);
    if(iter!=recordMap.end())  {
        PVRecordPtr pvRecord = (*iter).second;
        recordMap.erase(iter);
        return true;
    }
    return false;
}
```

Here is the PVRecord destructor:

```
PVRecord::~PVRecord()
{
    if(traceLevel>0) {
        cout << "~PVRecord() " << recordName << endl;
    }
    notifyClients();
}
```

**Comment by mrkraimer** [comment]
pull request #45 fixes the problem.
