### ISSUE TITLE
PVRecord data not being updated by local pvac::ClientChannel::put()

### ISSUE THREAD

**Issue by ralphlange** [epics-base/pvDatabaseCPP#52]
An ITER Bugzilla ticket has been opened against the EPICS Base component in CODAC Core System.

Apparently, behavior has changed between EPICS Base 7.0.2 (pvDatabase 4.4.0 / pvAccess 6.1.0 / pvData 7.1.0) and EPICS Base 7.0.3.1 (pvDatabase 4.5.1 / pvAccess 7.1.0 / pvData 8.0.1).

So far, the description in the Bugzilla ticket just says "PVStructure published on the network is not being updated." I.e. changes that the server application applies to the PVstructure data do not trigger updates on subscriptions from external PVA clients.

The change in behavior is being observed in several software modules that apparently all use pvDatabase.

We started investigating and should be able to provide more details soon.

**Comment by ralphlange** [comment]
For us, being in the release process for CODAC Core System 6.2, this is a relatively high priority issue. We need fix this in the next week or so, otherwise we'll have to roll back EPICS Base.

**Comment by mrkraimer** [comment]
On 1/22/20 4:41 AM, Ralph Lange wrote:
>
> An ITER Bugzilla ticket has been opened against the EPICS Base 
> component in CODAC Core System.
>
> Apparently, behavior has changed between EPICS Base 7.0.2 (pvDatabase 
> 4.4.0 / pvAccess 6.1.0 / pvData 7.1.0) and EPICS Base 7.0.3.1 
> (pvDatabase 4.5.1 / pvAccess 7.1.0 / pvData 8.0.1).
>
> So far, the description in the Bugzilla ticket just says "PVStructure 
> published on the network is not being updated." I.e. changes that the 
> server application applies to the PVstructure data do not trigger 
> updates on subscriptions from external PVA clients.
>
> The change in behavior is being observed in several software modules 
> that apparently all use pvDatabase.
>
> We started investigating and should be able to provide more details soon.
>

Please let me know as soon as You have more details.
In the meantime I will spend some time seeing if I can reproduce the 
problem.

**Comment by ralphlange** [comment]
Here's the list of pvDatabase changes we're looking at:
https://github.com/epics-base/pvDatabaseCPP/compare/4.4.0...4.5.1

**Comment by mrkraimer** [comment]
Can you provide

     pvinfo channelName

on some of the channels that have problems

**Comment by ralphlange** [comment]
Bertrand was able to provide a cut-down test program that is showing the issue. Here's the source that shows how we're using PVA: 
[pva-one-pps.zip](https://github.com/epics-base/pvDatabaseCPP/files/4103523/pva-one-pps.zip)

He writes (using EPICS 7.0.3.1):

> The small program has two implementations illustrating the two uses of the PVA server in SUP and MARTe.
> 
> The two implementations use PVDatabase and PVRecord on the server.
> 
> The first (SUP) uses PVRecord API to update/publish the structure. It works.
> The second (MARTe) uses PVAC API and the server structure does not change though the PutCallback::putBuild and putDone are successful ..
> 
> On the server side using the PVAC API ..
> 
> PutCallback::putBuild - Having in cache ..
> _1PPSStruct_t 
>     ulong time 1579773657103907869
>     ulong value 0
> 
> PutCallback::putDone - Done
> 
> But another client observing the structure elsewhere on the network does not see any update ..
> 
> $ pvget -m -v PVA-ONE-PPS
> PVA-ONE-PPS _1PPSStruct_t 
>     ulong time 0
>     ulong value 0

while using EPICS 7.0.2:

> $ pvget -m -v PVA-ONE-PPS
> PVA-ONE-PPS _1PPSStruct_t 
>     ulong time 0
>     ulong value 0
> PVA-ONE-PPS _1PPSStruct_t 
>     ulong time 1579774275634209256
>     ulong value 0
> PVA-ONE-PPS _1PPSStruct_t 
>     ulong time 1579774276635262776
>     ulong value 0
> PVA-ONE-PPS _1PPSStruct_t 
>     ulong time 1579774277636014751
>     ulong value 0

The test program uses a bunch of libraries from our "C++ Common" module. I started collecting everything needed into an EPICS module, but that will need a bit more time.

**Comment by ralphlange** [comment]
Just to clarify once more (more to me than to you, probably):

The server application (attachment) creates a structured PVRecord and starts the PVA server. Clients can connect.
When the server app uses the PVRecord interface to update the structure, everything works as expected. Clients get monitors.
When the server app uses the pvac interface to update the structure, clients do not get monitors.

**Comment by ralphlange** [comment]
More discussions, more clarification...

The wrong behaviour only appears when the server application tries to write to the PVRecord structure inside the same process ("local PVA") through the pvac interface. The pvac callbacks return success, but the data is not written to the PVRecord.

Bertrand will be providing a further stripped-down example that can be compiled and run in a "clean" EPICS context, including the utility headers he uses.

**Comment by ralphlange** [comment]
@mdavidsaver: How should we handle this issue? Move it to pvAccess? Create a dummy issue there, pointing to this one? Move it or not once we found where the culprit is located?

**Comment by ralphlange** [comment]
@mrkraimer @mdavidsaver 
Here's a complete minimal self-contained example showing the misbehaviour. (No external client needed.)
A data structure is being written into a pvRecord through local PVA.

Compiled against Base 7.0.2, you see the valued that is written and that is it received in the pvRecord.
```
PutCallback::putBuild - Sending from cache ..
_1PPSStruct_t 
    ulong time 1580206807431805409
    ulong value 0

Record::process - Having received ..
_1PPSStruct_t 
    ulong time 1580206807431805409
    ulong value 0

PVA-ONE-PPS Done
PutCallback::putBuild - Sending from cache ..
_1PPSStruct_t 
    ulong time 1580206808436546726
    ulong value 0

Record::process - Having received ..
_1PPSStruct_t 
    ulong time 1580206808436546726
    ulong value 0

PVA-ONE-PPS Done
```

Compiled against 7.0.3.1, the values do not arrive in the pvRecord.
```
PutCallback::putBuild - Sending from cache ..
_1PPSStruct_t 
    ulong time 1580207267738868787
    ulong value 0

Record::process - Having received ..
_1PPSStruct_t 
    ulong time 0
    ulong value 0

PVA-ONE-PPS Done
PutCallback::putBuild - Sending from cache ..
_1PPSStruct_t 
    ulong time 1580207268739725077
    ulong value 0

Record::process - Having received ..
_1PPSStruct_t 
    ulong time 0
    ulong value 0

PVA-ONE-PPS Done
```
[pva-test.tar.gz](https://github.com/epics-base/pvDatabaseCPP/files/4121874/pva-test.tar.gz)

**Comment by ralphlange** [comment]
@mrkraimer 
Key is that the example's BitSet has 0 set, which should be interpreted as "copy the whole structure".
I suspect that commit e1adfe30dfaa7faad81b46726479666516f4c4fb introduced the faulty behaviour.
See https://github.com/epics-base/pvDatabaseCPP/commit/e1adfe30dfaa7faad81b46726479666516f4c4fb#r36999076

Maybe the test coverage is too low.

**Comment by mrkraimer** [comment]
This was certainly a bug.
Thanks for finding and fixing it!!

**Comment by ralphlange** [comment]
Could you add a test for that? I tried to, but got lost in the complexity of the existing tests.
